# Generated by Django 5.1.2 on 2024-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
